version: "3.9"

services:
  db:
    image: postgres:15
    container_name: qwallets
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: qwallets
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
